description = "git commit"

prompt = """
- Make a commit of the pending changes we have. 
- Use conventional commits format and always use present tense.
- After executing commit you don't need to validate git status
"""
