theme = "rose_pine_moon" # or "onedark", "dracula"

[editor]
line-number = "relative"   # Absolute line number for current, relative for others
mouse = false              # Force yourself to use keyboard!
bufferline = "multiple"    # Show open buffers (tabs) at the top

[editor.cursor-shape]
insert = "bar"
normal = "block"
#select = "underline"

[editor.file-picker]
hidden = false             # Show hidden files (like .gitignore) by default

[keys.normal]
Z = { Z = ":write-quit", Q = ":quit!" }

